###Eureka启动端口号
server:
  port: 8090
#  port: 8090
####Eureka启动的host地址
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8090/eureka/
    ####是否向Eureka中注册，单机的情况下注册中心本不需要注册，集群的情况下注册中心需要相互注册
    register-with-eureka: true
    ####是否从Eureka抓取服务
    fetch-registry: true
spring:
  application:
    name: eureka-server